#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  flEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rangeFinder,    sensorSONAR_mm)
#pragma config(Sensor, dgtl12, coneButton,     sensorTouch)
#pragma config(Sensor, I2C_1,  backLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mobile,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          frontRight,    tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(145)

//adds functions for use without cluttering main program
#include "Vex_Competition_Includes.c"
#include "variableLibrary_01.h"
#include "autonLibrary_01.h"
#include "userControlsLibrary_03.h"
#include "user2ControlsLibrary_03.h"
#include "preAutonLibrary_01.h"

//FILE REVISION NOTES:
//dual joystick control

void pre_auton()
{
	//preAutonTasks();
	auton = 4;
	bStopTasksBetweenModes = true;
}

/*
AUTONOMOUS SET UP NOTES:

ALWAYS cycle the cortex before each test
Push arms in until front of claw is just in line with front of 4bar
Drop mobile lift until just slightly above the ground
Drop lift so that it lies just on top of the mobile lift
Use spacing tool with one end (lengthwise) at the glass wall, pushed against 10 point bar
Push side of robot until it connects with the spacing tool
Use LCD to select which autonomous you want to run
Test, record values, and repeat
*/

task autonomous()
{
	//Clear LCD
	resetEncoders();
	clearLCDLine(0);
	clearLCDLine(1);

	//Switch Case that runs the user choice
	switch(auton)
	{
	case 0:
		//One cone then move left
		nMotorEncoder(backLeft) = 0;
		lift(3200, 80);
		arms(2200, 80);
		dropLift(2500, 30);
		openClaw();
		holdOpen();
		timeDrop(100);
		armsIn(450, 90);
		closeClaw();
		turn(55, -60);
		move(400, 100);
		finished = true;
		break;
	case 1:
		//One cone then move right
		nMotorEncoder(backLeft) = 0;
		lift(3200, 80);
		arms(2200, 80);
		dropLift(2500, 30);
		openClaw();
		holdOpen();
		timeDrop(100);
		armsIn(450, 90);
		closeClaw();
		turn(55, 60);
		move(400, 100);
		finished = true;
		break;
	case 2:
		//Blue side two cones
		nMotorEncoder(backLeft) = 0;
		lift(170, 80);
		arms(110, 127);
		lift(92, -30);
		openClaw();
		holdOpen();
		arms(45, 90);
		timeDrop(100);
		move(3, 60);
		brake(-20);
		turn(19, -60);
		turnBrake(60);
		arms(42, 30);
		move(12.25, 70);
		brake(-10);
		closeClaw();
		wait1Msec(500);
		lift(170, 80);
		arms(110, 127);
		turn(85, 60);
		turnBrake(-5);
		move(1.2, -60);
		lift(85, 30);
		openClaw();
		holdOpen();
		move(10, -60);
		finished = true;
		break;
	case 3:
		//Red side two cones
		nMotorEncoder(backLeft) = 0;
		lift(170, 60);
		arms(125, 100);
		lift(85, 30);
		openClaw();
		holdOpen();
		arms(45, 90);
		lift(5, 20);
		move(3, 60);
		brake(-20);
		turn(19, 60);
		turnBrake(-60);
		arms(42, 30);
		move(12.25, 70);
		brake(-10);
		closeClaw();
		wait1Msec(500);
		lift(180, 60);
		arms(130, 90);
		turn(85, -60);
		turnBrake(5);
		move(1.2, -60);
		lift(85, 30);
		openClaw();
		holdOpen();
		move(10, -60);
		finished = true;
		break;
	case 4:
		//Blue side 20 point mobile
		nMotorEncoder(backLeft) = 0;
		clearTimer(T1);
		SensorValue(gyro) = 0;
		lift(2250, 80);
		move(1625, 100);
		brake(-60);
		wait1Msec(200);
		openClaw(); //drop first cone
		holdOpen();
		lift(3000, 80);
		closeClaw();
		arms(1075, 60);
		openClaw();
		holdOpen();
		dropLift(1950, 60);	//pick up second cone
		closeClaw();
		wait1Msec(500);
		lift(2565, 80);
		armsIn(400, 60);
		wait1Msec(200);
		openClaw(); //drop second cone
		lift(3600, 80);
		mobileLift(mobileCarry);
		backUp(1400, 120);
		turn(130, -120);
		turnBrake(120);
		move(250, 120);
		move(200, 60);
		turn(87, -120);
		turnBrake(120);
		move(350, 127);
		wait1Msec(250);
		moveLift(450, 127, mobileMax, 127);
		autonTime1 = time1[T1];
		backUp(600, 127);
		finished = true;
		break;
	case 5:
		//Red side 20 point
		nMotorEncoder(backLeft) = 0;
		clearTimer(T1);
		SensorValue(gyro) = 0;
		lift(2250, 80);
		move(1625, 100);
		brake(-60);
		wait1Msec(200);
		openClaw(); //drop first cone
		holdOpen();
		lift(3000, 80);
		closeClaw();
		arms(1075, 60);
		openClaw();
		holdOpen();
		dropLift(1950, 60);	//pick up second cone
		closeClaw();
		wait1Msec(500);
		lift(2565, 80);
		armsIn(400, 60);
		wait1Msec(200);
		openClaw(); //drop second cone
		lift(3600, 80);
		mobileLift(mobileCarry);
		backUp(1400, 120);
		turn(130, 120);
		turnBrake(-120);
		move(250, 120);
		move(200, 60);
		turn(87, 120);
		turnBrake(-120);
		move(350, 127);
		wait1Msec(250);
		moveLift(450, 127, mobileMax, 127);
		autonTime1 = time1[T1];
		backUp(600, 127);
		finished = true;
		break;
	case 6:
		//Blue side 10 point mobile
		nMotorEncoder(backLeft) = 0;
		clearTimer(T1);
		SensorValue(gyro) = 0;
		lift(2435, 80);
		move(1620, 100);
		brake(-60);
		wait1Msec(250);
		openClaw(); //drop first cone
		holdOpen();
		lift(3000, 80);
		closeClaw();
		arms(1075, 60);
		openClaw();
		holdOpen();
		dropLift(1950, 60);	//pick up second cone
		closeClaw();
		wait1Msec(500);
		lift(2565, 80);
		armsIn(400, 60);
		wait1Msec(250);
		openClaw(); //drop second cone
		lift(3600, 80);
		mobileLift(mobileCarry);
		backUp(750, 120);
		backUp(100, 30);
		turn(165, -120);
		turnBrake(120);
		move(450, 60);
		turn(40, -120);
		turnBrake(120);
		moveLift(375, 80, mobileMax, 120);
		wait1Msec(500);
		backUp(400, 127);
		finished = true;
		break;
	case 7:
		//Red side 10 point mobile
		nMotorEncoder(backLeft) = 0;
		clearTimer(T1);
		SensorValue(gyro) = 0;
		lift(2435, 80);
		move(1620, 100);
		brake(-60);
		wait1Msec(250);
		openClaw(); //drop first cone
		holdOpen();
		lift(3000, 80);
		closeClaw();
		arms(1075, 60);
		openClaw();
		holdOpen();
		dropLift(1900, 60);	//pick up second cone
		closeClaw();
		wait1Msec(500);
		lift(2565, 80);
		armsIn(400, 60);
		wait1Msec(250);
		openClaw(); //drop second cone
		lift(3600, 80);
		mobileLift(mobileCarry);
		backUp(725, 120);
		backUp(100, 30);
		turn(165, 120);
		turnBrake(-120);
		move(575, 60);
		turn(40, 120);
		turnBrake(-120);
		moveLift(425, 80, mobileMax, 120);
		wait1Msec(500);
		backUp(415, 127);
		finished = true;
		break;
	}
	AutonomousCodePlaceholderForTesting();  // DO NOT REMOVE THIS
}

task usercontrol()
{
	SensorValue(armPot) = 0;
	while(true)
	{
		liftControls();

		internal();

		intakeControls();

		armsControls();

		user2();

		returnValues();
	}
}
